import {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BookOpen,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Fullscreen,
  Grid3X3,
  Hash,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  Map,
  Maximize2,
  Menu,
  Minimize2,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  ShoppingCart,
  Sidebar,
  SlidersHorizontal,
  Star,
  Sun,
  Table,
  Tag,
  Trash2,
  Truck,
  Upload,
  User,
  UserCheck,
  UserCircle,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

export type IconComponent = LucideIcon;

export {
  AlertCircle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  Bell,
  BookOpen,
  Building2,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  CreditCard,
  DollarSign,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Fullscreen,
  Grid3X3,
  Hash,
  HelpCircle,
  Home,
  Image,
  Inbox,
  Info,
  LayoutDashboard,
  Loader2,
  LogOut,
  Mail,
  Map,
  Maximize2,
  Menu,
  Minimize2,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Package,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  ShoppingCart,
  Sidebar,
  SlidersHorizontal,
  Star,
  Sun,
  Table,
  Tag,
  Trash2,
  Truck,
  Upload,
  User,
  UserCheck,
  UserCircle,
  Users,
  X,
};

export const Icons = {
  logo: () => (
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="size-6">
      <path d="M3 9L12 2L21 9V20C21 20.5304 20.7893 21.0391 20.4142 21.4142C20.0391 21.7893 19.5304 22 19 22H5C4.46957 22 3.96086 21.7893 3.58579 21.4142C3.21071 21.0391 3 20.5304 3 20V9Z" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" fill="currentColor" fillOpacity="0.2"/>
      <path d="M9 22V12H15V22" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  ),
  fantasticAdmin: () => (
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" className="size-5">
      <rect x="2" y="2" width="20" height="20" rx="4" stroke="currentColor" strokeWidth="2"/>
      <path d="M7 12L10 15L17 8" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
    </svg>
  ),
};
